spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/test_db?authSource=admin
    redis:
      host: localhost
      port: 6379
      timeout:
        millis: 100
      ttl:
        minutes: 3
  kafka:
    bootstrap-servers: http://localhost:29092
mongock:
  migration-scan-package: com.example.passmanagersvc.migration
nats:
  spring:
    io:
      nats:
        client:
          servers: nats://localhost:4222
server:
  servlet:
    context-path: /api/v1
  port: 8081
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
