services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APPLICATION_NAME: PassManagingApplication
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo
      MONGODB_DATABASE: test_db
      MONGODB_USER: root
      MONGODB_PASSWORD: example
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  db_data:
