spring:
  application:
    name: ${APPLICATION_NAME}
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin
mongock:
  migration-scan-package: com.example.passmanager.migration
server:
  servlet:
    context-path: /api/v1
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
