spring:
  application:
    name: ${APPLICATION_NAME}
  data:
    mongodb:
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
server:
  servlet:
    context-path: /api/v1