server:
  servlet:
    context-path: /api/v1
nats:
  spring:
    io:
      nats:
        client:
          servers: nats://localhost:4222
grpc:
  server:
    port: 9091
    security:
      enabled: false
