apiVersion: v1
kind: ConfigMap
metadata:
  name: pass-manager-app-configmap
data:
  mongo_port: "27017"
  mongo_host: "mongodb-service"
  mongo_database: "test_db"
  nats_uri: "nats://nats-service:4222"
