name: Kotlin CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'

env:
  gradle_cmd: ./gradlew --parallel --build-cache
    -PAWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
    -PAWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
    -Prepository=${{ secrets.PRIVATEMAVENREPO }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start containers
        run: docker compose --profile test up -d

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}

      - name: Build with Gradle Wrapper
        run: ${gradle_cmd} build -x deltaCoverage

      - name: Perform Delta coverage
        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
        run: ${gradle_cmd} deltaCoverage -PdiffBase="refs/remotes/origin/$GITHUB_BASE_REF"

      - name: Post comment
        uses: gw-kit/delta-coverage-plugin/actions/delta-coverage-report@main
        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
        continue-on-error: true
        with:
          title: 'Delta Coverage Report'
          delta-coverage-report: build/reports/coverage-reports/delta-coverage/report.md
